openapi: 3.0.3
info:
  title: Slides Write API
  version: "1.0.0"
servers:
  - url: https://slides-content-api-zymqrul26q-uc.a.run.app
paths:
  /slides/write:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [document_id, slides_data_json]
              properties:
                document_id: {type: string}
                slides_data_json: {type: string}
      responses:
        200: {description: Success}