openapi: 3.0.3
info:
  title: Slides Write API
  version: "1.0.0"
servers:
  - url: https://slides-content-api-zymqrul26q-uc.a.run.app
paths:
  /slides/write:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [document_id, use_cases]
              properties:
                document_id: {type: string}
                use_cases: 
                  type: array
                  items: 
                    type: object
                    properties:
                      number: {type: integer}
                      title: {type: string}
                      description: {type: string}
                      department: {type: string}
                      impact: {type: string}
                      data_sources: {type: string}
      responses:
        200: {description: Success}